name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region ap-south-1 --name skillpulse-dev

      - name: Deploy manifests
        run: |
          kubectl apply -f k8s/core/
          kubectl apply -f k8s/mysql/
          kubectl apply -f k8s/skillpulse/

      - name: Update backend image
        run: |
          kubectl set image deployment/backend backend=486036174293.dkr.ecr.ap-south-1.amazonaws.com/skillpulse-backend:latest -n skillpulse

      - name: Update frontend image
        run: |
          kubectl set image deployment/frontend frontend=486036174293.dkr.ecr.ap-south-1.amazonaws.com/skillpulse-frontend:latest -n skillpulse
